site_name: Trabajo IA

docs_dir: 'md'
site_dir: 'docs'

theme: 
  name: materia
  favicon: img/favicon.png

nav: 
  - Inicio: index.md 
  - Origenes: origen.md
  - Vida Cotidiana: vida_cotidiana.md
  - Evoluci√≥n: evo.md
  - Impacto: 
    - 5.1 - Impacto: seccion5/subseccion5_1.md
    - 5.2 - Impacto: seccion5/subseccion5_2.md
